[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = [
  "npm install --production=false --ignore-scripts --no-audit --no-fund",
  "cd frontend && npm install --legacy-peer-deps --no-audit --no-fund && cd .."
]

[phases.build]
cmds = [
  "cd frontend && npm run build && cd .."
]

[start]
cmd = "npm start"
