[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = [
  "npm ci",
  "cd frontend && npm ci && cd .."
]

[phases.build]
cmds = [
  "cd frontend && npm run build && cd .."
]

[start]
cmd = "npm start"
